Practica09MVC/Models/ErrorViewModel.cs
namespace Practica09MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Practica09MVC/Models/equipos.cs
using System.ComponentModel.DataAnnotations;

namespace Practica09MVC.Models
{
    public class equipos
    {
        [Key]
        public int id_equipos { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int tipo_equipo_id { get; set; }
        public int marca_id { get; set; }
        public string modelo { get; set; }
        public int anio_compra { get; set; }
        public double costo { get; set; }
        public int vida_util { get; set; }
        public int estado_equipo_id { get; set; }
        public string estado { get; set; }

    }
}

Practica09MVC/Models/equiposDbContext.cs
using Microsoft.EntityFrameworkCore;
namespace Practica09MVC.Models
{
    public class equiposDbContext : DbContext
    {
        public equiposDbContext(DbContextOptions options) : base(options) 
        {
        }

        public DbSet<marcas> marcas { get; set; }
        public DbSet<equipos> equipos { get; set; }
    }
}

Practica09MVC/Models/estados_equipo.cs
using System.ComponentModel.DataAnnotations;

namespace Practica09MVC.Models
{
    public class estados_equipo
    {
        [Key]
        [Display(Name = "ID")]
        public int id_estados_equipo { get; set; }
        [Display(Name = "Descripcion")]
        public string? descripcion { get; set; }
        [Display(Name = "Estado")]
        public string? estado { get; set; }
    }
}

Practica09MVC/Models/marcas.cs
using System.ComponentModel.DataAnnotations;

namespace Practica09MVC.Models
{
    public class marcas
    {
        [Key]
        [Display(Name = "ID")]
        public int id_marcas { get; set; }
        [Display(Name = "Nombre de la Marca")]
        public string? nombre_marca { get; set; }
        [Display(Name = "Estado")]
        public string? estados { get; set; }
    }
}

Practica09MVC/Controllers/EquiposController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Practica09MVC.Models;

namespace Practica09MVC.Controllers
{
    public class EquiposController : Controller
    {
        private readonly equiposDbContext _equiposDbContext;

        public EquiposController(equiposDbContext equiposDbContext) 
        {
            _equiposDbContext= equiposDbContext;
        }
        public IActionResult Index()
        {
            var listaDeMarcas = (from m in _equiposDbContext.marcas
                                 select m).ToList();
            ViewData["listadoDeMarcas"] = new SelectList(listaDeMarcas, "id_marcas", "nombre_marca");

            var listadoDeEquipos = (from e in _equiposDbContext.equipos
                                    join m in _equiposDbContext.marcas on e.marca_id equals m.id_marcas
                                    select new
                                    {
                                        nombre = e.nombre,
                                        descripcion = e.descripcion,
                                        marca_id = e.marca_id,
                                        marca_nombre = m.nombre_marca
                                    }).ToList();

            ViewData["listadoEquipo"] = listadoDeEquipos;
            return View();
        }

        public IActionResult CrearEquipos(equipos nuevoEquipo) 
        {
            _equiposDbContext.Add(nuevoEquipo);
            _equiposDbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Practica09MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Practica09MVC.Models;
using System.Diagnostics;

namespace Practica09MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Practica09MVC/Views/Equipos/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Mantenimiento de Equipos</h1>
<br />
<form asp-action="CrearEquipos">
    <div class="form-group row mb-4">
        <div class="col-sm-2">
            <label>Nombre</label>
        </div>
        <div class="col-sm-4">
            @Html.TextBox("nombre", "", new {@class="form-control"})
        </div>
        <div class="col-sm-2">
            @Html.Label("lblDescripcion", "Descripción")
        </div>
        <div class="col-sm-4">
            @Html.TextArea("descripcion", "", new {@class="form-control", @placeHolder="Ingrese la descripción"})
        </div>
        <div class="col-sm-4">
            @Html.DropDownList("marca_id", ViewData["listadoDeMarcas"] as SelectList, "Seleccione una marca", new {@class="form-control"})
        </div>
        <div class="form-group row mb-4">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                <input type="submit" class="btn btn-primary" value="Guardar"/>
            </div>
        </div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Equipo</th>
                    <th>Descripcion</th>
                    <th>Marca</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var equipo in (IEnumerable <dynamic>)ViewData["listadoEquipo"])
                {
                    <tr>
                        <td>@equipo.nombre</td>
                        <td>@equipo.descripcion</td>
                        <td>@equipo.marca_nombre</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</form>

Practica09MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Practica09MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica09MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Practica09MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica09MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Equipos" asp-action="Index">Equipos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Practica09MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>